name: doctemplatex
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - expat=2.6.2
  - icu=73.1
  - libcxx=14.0.6
  - libffi=3.4.4
  - libiconv=1.16
  - libxml2=2.10.4
  - libxslt=1.1.37
  - lxml=5.2.1
  - ncurses=6.4
  - openssl=3.0.13
  - pip=24.0
  - python=3.12.3
  - python-docx=1.1.2
  - readline=8.2
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - typing_extensions=4.11.0
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
prefix: ./env/doctemplatex
